Document: trng
Title: Debian trng Manual
Author: <insert document author here>
Abstract: This manual describes what trng is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/trng/trng.sgml.gz

Format: postscript
Files: /usr/share/doc/trng/trng.ps.gz

Format: text
Files: /usr/share/doc/trng/trng.text.gz

Format: HTML
Index: /usr/share/doc/trng/html/index.html
Files: /usr/share/doc/trng/html/*.html
